version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  customerservice:
    image: larissamxl/customerservice
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - RABBITMQ_HOST=rabbitmq
